basketapp/urls.py
from django.urls import path

from .views import cart_detail, cart_add, cart_remove

app_name = 'basketapp'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:pk>', cart_add, name='cart_add'),
    path('remove/<int:pk>', cart_remove, name='cart_remove')
]

jw_films/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('productapp.urls', namespace='productapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('order/', include('orderapp.urls', namespace='orderapp')),
    path('', include('mainapp.urls', namespace='mainapp')),
]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import index, contacts

app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productapp/urls.py
from django.urls import path

from .views import ProductByCategoryListView, ProductListView, ProductDetailView, PriceListView

app_name = 'productapp'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('cat/<int:pk>', ProductByCategoryListView.as_view(), name='products_by_category'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='products_detail'),
    path('price_list', PriceListView.as_view(), name='price_list'),
]

templates/includes/inc_footer.html
<div>
    <nav class="navbar navbar-expand-md bg-light">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-link">
                        &copy; {{ company.title }}
                    </li>
                    {% for item in company.get_phone_numbers %}
                        <li class="nav-item">
                            <a class="nav-link" href="tel:{{ item }}">{{ item }}</a>
                        </li>
                    {% endfor %}
                    <li class="nav-item">
                        <a class="nav-link" href="mailto:{{ company.email }}">{{ company.email }}</a>
                    </li>
                </ul>
                <div>

                    <a class="nav-link" href="https://yandex.ru/maps/?text={{ company.address }}"
                       target="_blank">{{ company.address }}</a>
                </div>
            </div>
        </div>
    </nav>
</div>

templates/includes/inc_navigation.html
{% load static %}
<div>
    <nav class="navbar navbar-expand-sm bg-light">
        <div class="container-fluid">
            <img src="/media/{{ company.logo }}" alt="" style="max-width: 150px;">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'productapp:products' %}">Каталог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'productapp:price_list' %}">Прайс-лист</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
                    </li>
                </ul>
                <div>
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            Корзина:
                            <a href="{% url 'basketapp:cart_detail' %}" class="link-dark">
                                {{ cart.get_total_product_amount }} товар(ов), {{ cart.get_total_price }} руб.
                            </a>
                        {% else %}
                            Корзина пуста
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </nav>
</div>