basketapp/urls.py
from django.urls import path

from .views import cart_detail, cart_add, cart_remove

app_name = 'basketapp'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:pk>', cart_add, name='cart_add'),
    path('remove/<int:pk>', cart_remove, name='cart_remove')
]

jw_films/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('productapp.urls', namespace='productapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('order/', include('orderapp.urls', namespace='orderapp')),
    path('', include('mainapp.urls', namespace='mainapp')),
]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import index, contacts

app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orderapp/urls.py
from django.urls import path

from orderapp.views import order_create

app_name = 'orderapp'

urlpatterns = [
    path('create/', order_create, name='order_create'),
]

productapp/urls.py
from django.urls import path

from .views import ProductByCategoryListView, ProductListView, ProductDetailView, PriceListView

app_name = 'productapp'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('cat/<int:pk>', ProductByCategoryListView.as_view(), name='products_by_category'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='products_detail'),
    path('price_list', PriceListView.as_view(), name='price_list'),
]

basketapp/models.py
from django.db import models

# Create your models here.

basketapp/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

basketapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from productapp.models import ProductList
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, pk):
    """Создание корзины"""
    cart = Cart(request)
    product = get_object_or_404(ProductList, pk=pk)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update']
        )

    return redirect('basketapp:cart_detail')


def cart_remove(request, pk):
    """ Удаление корзины """
    cart = Cart(request)
    product = get_object_or_404(ProductList, id=pk)
    cart.remove(product)
    return redirect('basketapp:cart_detail')


def cart_detail(request):
    """ Детали корзины """
    cart = Cart(request)
    return render(request, 'basketapp/cart_detail.html', {'object': cart})

templates/basketapp/cart_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>Ваша корзина</h1>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Цена</th>
            <th>Сумма</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for item in object %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{% url 'productapp:products_detail' product.pk %}">
                            <img src="/media/products_img/{{ product.image }}" alt="" style="width: 50px;">
                        </a>
                    </td>
                    <td>
                        <b>{{ product.title }}</b><br>
                        {{ product.category }}
                    </td>
                    <td>{{ item.quantity }} м.п.</td>
                    <td>{{ item.price }} руб.</td>
                    <td>{{ item.total_price }} руб.</td>
                    <td>
                        <a href="{% url 'basketapp:cart_remove' product.id %}">Удалить</a>
                    </td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr>
            <td>Всего</td>
            <td colspan="3"></td>
            <td>{{ object.get_total_price }} руб.</td>
        </tr>
        </tbody>
    </table>
    <p>
        <a href="{% url 'productapp:products' %}" class="button light">Продолжить покупки</a>
        <a href="{% url 'orderapp:order_create' %}" class="button">Оформить</a>
    </p>
{% endblock %}