basketapp/urls.py
from django.urls import path

from .views import cart_detail, cart_add, cart_remove

app_name = 'basketapp'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:pk>', cart_add, name='cart_add'),
    path('remove/<int:pk>', cart_remove, name='cart_remove')
]

jw_films/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('productapp.urls', namespace='productapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('order/', include('orderapp.urls', namespace='orderapp')),
    path('', include('mainapp.urls', namespace='mainapp')),
]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import index, contacts

app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productapp/urls.py
from django.urls import path

from .views import ProductByCategoryListView, ProductListView, ProductDetailView, PriceListView

app_name = 'productapp'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('cat/<int:pk>', ProductByCategoryListView.as_view(), name='products_by_category'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='products_detail'),
    path('price_list', PriceListView.as_view(), name='price_list'),
]

productapp/models.py
import os

from django.conf.global_settings import MEDIA_ROOT
from django.db import models


class CategoryList(models.Model):
    title = models.CharField(verbose_name='Название', max_length=128)
    description = models.TextField(verbose_name='Описание', default='', blank=True)
    image = models.ImageField(upload_to='category_img', blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

    def get_products_by_category(self):
        return ProductList.objects.filter(category=self.pk)


class ProductList(models.Model):
    title = models.CharField(verbose_name='Название', max_length=128)
    category = models.ForeignKey(CategoryList, verbose_name='Категория', on_delete=models.PROTECT)
    image = models.ImageField(upload_to='products_img', blank=True, default=os.path.join(MEDIA_ROOT, 'default_img.jpg'))
    price = models.DecimalField(verbose_name='Цена', blank=True, decimal_places=2, max_digits=7, default=0)
    description = models.TextField(verbose_name='Описание', max_length=512, blank=True)
    is_active = models.BooleanField(verbose_name='Активно', default=True)
    is_sale = models.BooleanField(verbose_name='Распродажа', default=False)
    sale_price = models.DecimalField(verbose_name='Цена распродажи', blank=True,
                                     decimal_places=2, max_digits=7, default=0)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.is_sale:
            self.sale_price = self.price
        super().save(*args, **kwargs)

productapp/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView

from basketapp.forms import CartAddProductForm
from productapp.models import ProductList, CategoryList


class ProductListView(ListView):
    """ Каталог товаров """
    model = ProductList
    template_name = 'productapp/index.html'
    context_object_name = 'objects'

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['title'] = 'Каталог товаров'
        context['category_links'] = CategoryList.objects.values_list('pk', 'title')
        return context


class ProductByCategoryListView(ProductListView):
    """  Каталог товаров по категориям """
    def get_queryset(self):
        qs = ProductList.objects.filter(is_active=True)
        if self.kwargs['pk'] is not None:
            category = get_object_or_404(CategoryList, pk=self.kwargs['pk'])
            qs = qs.filter(category=category)
        return qs

    def get_context_data(self, **kwargs):
        context = super(ProductByCategoryListView, self).get_context_data(**kwargs)
        context['category'] = get_object_or_404(CategoryList, pk=self.kwargs['pk'])
        return context


class ProductDetailView(DetailView):
    """ Карточки товаров """
    model = ProductList
    template_name = 'productapp/product_detail.html'
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['cat_prods'] = ProductList.objects.filter(category=self.object.category)
        context['cart_product_form'] = CartAddProductForm()
        return context


class PriceListView(ListView):
    """ Прайс-лист """
    model = CategoryList
    template_name = 'productapp/price_list.html'
    context_object_name = 'objects'

    def get_context_data(self, **kwargs):
        context = super(PriceListView, self).get_context_data(**kwargs)
        context['title'] = 'Прайс-лист'
        return context

templates/productapp/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container" xmlns="http://www.w3.org/1999/html">
        <div>
            Серии:
            <a href="{% url 'productapp:products' %}" class="link-primary" style="margin-left: 10px;">Все</a>
            {% for category in category_links %}
                <a href="{% url 'productapp:products_by_category' category.0 %}"
                   class="link-primary" style="margin-left: 10px;">{{ category.1 }}</a>
            {% endfor %}
        </div>
        <hr>
        {% if category %}
            <div class="container">
            <img src="/media/{{ category.image }}" class="img-fluid mx-auto d-block"
                             alt="{{ category_img.title }}">
            {{ category.description|linebreaks }}
            </div>
        {% endif %}
        <div class="d-flex justify-content-around flex-wrap">

            {% for object in objects %}
                <div class="card" style="min-width: 200px; max-width: 300px; margin-top: 15px;">
                    <a href="{% url 'productapp:products_detail' object.pk %}">
                        <img src="/media/products_img/{{ object.image }}" class="card-img-top img-thumbnail"
                             alt="{{ object.title }}">
                    </a>
                    <div class="card-body">
                        <a href="{% url 'productapp:products_detail' object.pk %}"
                           class="link-dark" style="text-decoration: none">
                            <div>
                                <h5 class="card-title">{{ object.title }}
                                    {% if object.is_sale %}
                                        <span style="color: red;">АКЦИЯ!</span>
                                    {% endif %}
                                </h5>
                                <p class="card-text">
                                Цена:
                                    {% if object.is_sale %}
                                        <s><small class="text-muted">от {{ object.price }}</small></s>
                                        от <span style="color: red; font-weight: bold;">{{ object.sale_price }}</span> руб.
                                    {% else %}
                                        <span>от {{ object.price }} руб.</span>
                                    {% endif %}
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="d-grid gap-2">
                        <a href="{% url 'productapp:products_detail' object.pk %}" class="btn btn-outline-primary btn-buy" type="button">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

templates/productapp/price_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        {% for object in objects %}
            <h4>{{ object.title }}</h4>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Описание</th>
                    <th>Цена</th>
                    <th>Ссылка</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object.get_products_by_category %}
                    <tr>
                        <td>{{ item.title }}</td>
                        <td>
                            {{ item.description }}
                            {%  if item.is_sale %}
                                <span style="color: red; font-weight: bold">АКЦИЯ!</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.is_sale %}
                                <span style="color: red; font-weight: bold">{{ item.sale_price }}</span>
                            {% else %}
                                <span>{{ item.price }}</span>
                            {% endif %}</td>
                        <td>
                            <a href="{% url 'productapp:products_detail' item.pk %}">Подробнее</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endfor %}
    </div>
{% endblock %}

templates/productapp/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <div class="card mb-3 border-0" style="max-width: 100%; padding-top: 15px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="/media/products_img/{{ object.image }}"
                         class="img-fluid rounded-start"
                         alt="{{ object.title }}"
                         style="width: 1000px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h3 class="card-title">{{ object.title }}, Серия {{ object.category.title }}</h3>
                        <p class="card-text">{{ object.description|linebreaks }}</p>
                        <p class="card-text"><b>Цена:</b>
                            {% if object.is_sale %}
                                <s><small class="text-muted">{{ object.price }}</small></s>
                                <span>{{ object.sale_price }}</span>
                            {% else %}
                                <span>от {{ object.price }} руб.</span>
                            {% endif %}</p>
                        <div>
                            <form action="{% url 'basketapp:cart_add' object.pk %}" id="form_amount_prods"
                                  class="row g-3" method="post">
                                <div class="col-auto">
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                </div>
                                <div class="col-auto">
                                    <button class="btn btn-outline-primary" type="submit">В корзину</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <h4>Товары этой категории</h4>
        <div class="container d-flex justify-content-around flex-wrap">
            {% for item in cat_prods %}
                <div class="card" style="min-width: 200px; max-width: 300px; margin-top: 15px;">
                    <a href="{% url 'productapp:products_detail' item.pk %}">
                        <img src="/media/products_img/{{ item.image }}" class="card-img-top img-thumbnail"
                             alt="{{ object.title }}">
                    </a>
                    <div class="card-body">
                        <a href="{% url 'productapp:products_detail' item.pk %}"
                           class="link-dark" style="text-decoration: none">
                            <div>
                                <h5 class="card-title">{{ item.title }}
                                    {% if item.is_sale %}
                                        <span style="color: red;">АКЦИЯ!</span>
                                    {% endif %}
                                </h5>
                                <p class="card-text">
                                    Цена:
                                    {% if item.is_sale %}
                                        <s><small class="text-muted">{{ item.price }}</small></s>
                                        от <span style="color: red; font-weight: bold;">{{ item.sale_price }}</span> руб.
                                    {% else %}
                                        <span>от {{ item.price }} руб.</span>
                                    {% endif %}
                                </p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}